from __future__ import annotations

from datetime import datetime, timezone

from setupvault.core.snapshot import Snapshot


def render_html(snapshot: Snapshot) -> str:
    """Render a snapshot as a standalone HTML profile page.

    Args:
        snapshot: The snapshot to render.

    Returns:
        A complete HTML document as a string.
    """
    sys_info = snapshot.system
    pkg = snapshot.packages

    system_rows = _system_table(sys_info)
    theme_block = _theme_section(snapshot)
    font_block = _font_section(snapshot)
    dotfiles_section = _dotfiles_section(snapshot)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SetupVault Profile — {sys_info.hostname}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
    background: #f8f9fa; color: #212529; line-height: 1.6; padding: 2rem;
  }}
  .container {{ max-width: 960px; margin: 0 auto; }}
  header {{ text-align: center; margin-bottom: 2rem; }}
  h1 {{ font-size: 2rem; color: #1a73e8; }}
  .meta {{ color: #6c757d; font-size: 0.9rem; margin-top: 0.5rem; }}
  .card {{ background: #fff; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,.1); padding: 1.5rem; margin-bottom: 1.5rem; }}
  h2 {{ font-size: 1.25rem; margin-bottom: 1rem; color: #343a40; border-bottom: 2px solid #e9ecef; padding-bottom: .5rem; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th, td {{ text-align: left; padding: .5rem .75rem; border-bottom: 1px solid #e9ecef; font-size: .9rem; }}
  th {{ font-weight: 600; color: #495057; width: 40%; }}
  td {{ color: #212529; }}
  .count-grid {{ display: flex; gap: 1rem; flex-wrap: wrap; }}
  .count-item {{ background: #e9ecef; border-radius: 6px; padding: 1rem; text-align: center; flex: 1; min-width: 80px; }}
  .count-item .num {{ font-size: 1.5rem; font-weight: 700; color: #1a73e8; }}
  .count-item .label {{ font-size: .75rem; color: #6c757d; }}
  .tag {{ display: inline-block; background: #e7f3ff; color: #1a73e8; font-size: .75rem; padding: .2rem .5rem; border-radius: 4px; margin: .15rem; }}
  .dotfile {{ font-family: 'SF Mono', 'Fira Code', monospace; font-size: .85rem; background: #f1f3f5; padding: .3rem .5rem; border-radius: 4px; margin: .2rem 0; display: inline-block; }}
  .warnings {{ color: #856404; background: #fff3cd; border: 1px solid #ffeeba; border-radius: 4px; padding: 1rem; margin-top: 1rem; }}
  footer {{ text-align: center; color: #6c757d; font-size: .8rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e9ecef; }}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>SetupVault Profile</h1>
    <div class="meta">
      <strong>{sys_info.hostname}</strong> &middot; {sys_info.distribution.name} {sys_info.distribution.version}
      &middot; Created {_fmt_date(snapshot.created_at)}
    </div>
  </header>

  <div class="card">
    <h2>System</h2>
    <table>
{system_rows}
    </table>
  </div>

  <div class="card">
    <h2>Packages</h2>
    <div class="count-grid">
      <div class="count-item"><div class="num">{_v(pkg.counts.official)}</div><div class="label">Official</div></div>
      <div class="count-item"><div class="num">{_v(pkg.counts.aur)}</div><div class="label">AUR</div></div>
      <div class="count-item"><div class="num">{_v(pkg.counts.third_party)}</div><div class="label">Third-party</div></div>
      <div class="count-item"><div class="num">{_v(pkg.counts.flatpak)}</div><div class="label">Flatpak</div></div>
      <div class="count-item"><div class="num">{_v(pkg.counts.snap)}</div><div class="label">Snap</div></div>
      <div class="count-item"><div class="num">{pkg.counts.total}</div><div class="label">Total</div></div>
    </div>
    {_package_list_html(pkg.official, "Official")}
    {_package_list_html(pkg.aur, "AUR")}
    {_package_list_html(pkg.third_party, "Third-party")}
  </div>

  {theme_block}
  {font_block}
  {dotfiles_section}
</div>
<footer>Generated by SetupVault on {_fmt_date(datetime.now(timezone.utc).isoformat())}</footer>
</body>
</html>"""


def _system_table(sys_info: object) -> str:
    from setupvault.core.snapshot import SystemInfo

    s = sys_info if isinstance(sys_info, SystemInfo) else SystemInfo.__new__(SystemInfo)
    rows = [
        ("Distribution", f"{s.distribution.name} {s.distribution.version}"),
        ("Kernel", s.kernel.release),
        ("Architecture", s.architecture),
        ("Hostname", s.hostname),
    ]
    uptime_secs = getattr(s, "uptime_seconds", None)
    if uptime_secs is not None:
        hours = uptime_secs // 3600
        minutes = (uptime_secs % 3600) // 60
        rows.append(("Uptime", f"{hours}h {minutes}m"))
    return "".join(f"      <tr><th>{k}</th><td>{v}</td></tr>\n" for k, v in rows)


def _theme_section(snapshot: Snapshot) -> str:
    theme = snapshot.themes
    if not theme:
        return ""

    lines = ['  <div class="card">', "    <h2>Themes</h2>", "    <table>"]
    if theme.gtk:
        g = theme.gtk
        if g.theme:
            lines.append(
                f'      <tr><th>GTK Theme</th><td><span class="tag">{_e(g.theme)}</span></td></tr>'
            )
        if g.icon_theme:
            lines.append(
                f'      <tr><th>GTK Icons</th><td><span class="tag">{_e(g.icon_theme)}</span></td></tr>'
            )
        if g.cursor_theme:
            lines.append(
                f'      <tr><th>Cursor</th><td><span class="tag">{_e(g.cursor_theme)}</span></td></tr>'
            )
        if g.font_name:
            lines.append(f"      <tr><th>GTK Font</th><td>{_e(g.font_name)}</td></tr>")
        if g.color_scheme:
            lines.append(
                f'      <tr><th>Color Scheme</th><td><span class="tag">{_e(g.color_scheme)}</span></td></tr>'
            )
    if theme.qt:
        q = theme.qt
        if q.theme:
            lines.append(
                f'      <tr><th>Qt Theme</th><td><span class="tag">{_e(q.theme)}</span></td></tr>'
            )
        if q.icon_theme:
            lines.append(
                f'      <tr><th>Qt Icons</th><td><span class="tag">{_e(q.icon_theme)}</span></td></tr>'
            )
        if q.font_name:
            lines.append(f"      <tr><th>Qt Font</th><td>{_e(q.font_name)}</td></tr>")
    lines.append("    </table>")
    lines.append("  </div>")
    return "\n".join(lines)


def _font_section(snapshot: Snapshot) -> str:
    font_info = snapshot.fonts
    if not font_info:
        return ""

    lines = ['  <div class="card">', "    <h2>Fonts</h2>"]
    if font_info.user_fonts:
        lines.append(f"    <p><strong>User fonts ({len(font_info.user_fonts)}):</strong></p>")
        lines.append("    <p>")
        for f in font_info.user_fonts:
            lines.append(f'      <span class="tag">{_e(f.family)}</span>')
        lines.append("    </p>")
    if font_info.config:
        cfg = font_info.config
        parts = []
        if cfg.hinting:
            parts.append(f"hinting={cfg.hinting}")
        if cfg.antialiasing is not None:
            parts.append(f"antialiasing={_v(cfg.antialiasing)}")
        if parts:
            lines.append(f"    <p><strong>Rendering:</strong> {', '.join(parts)}</p>")
    lines.append("  </div>")
    return "\n".join(lines)


def _dotfiles_section(snapshot: Snapshot) -> str:
    if not snapshot.dotfiles:
        return ""
    lines = ['  <div class="card">', "    <h2>Dotfiles</h2>", "    <p>"]
    for df in snapshot.dotfiles:
        h = df.hash[:12] if df.hash else "—"
        lines.append(
            f'      <span class="dotfile" title="SHA-256: {df.hash}">{_e(df.path)} ({h}…)</span>'
        )
    lines.append("    </p>")
    lines.append("  </div>")
    return "\n".join(lines)


def _package_list_html(packages: object, title: str) -> str:
    pkg_list = packages if isinstance(packages, (list, tuple)) else []
    if not pkg_list:
        return ""
    lines = [f'    <h3 style="margin-top:1rem;font-size:1rem;">{title}</h3>', "    <p>"]
    for p in pkg_list:
        name = getattr(p, "name", str(p))
        ver = getattr(p, "version", None) or ""
        label = f"{name} {ver}" if ver else name
        lines.append(f'      <span class="tag">{_e(label)}</span>')
    lines.append("    </p>")
    return "\n".join(lines)


def _fmt_date(iso: str) -> str:
    try:
        dt = datetime.fromisoformat(iso)
        return dt.strftime("%B %d, %Y at %H:%M")
    except (ValueError, TypeError):
        return iso


def _e(val: object) -> str:
    """HTML-escape a string value."""
    s = str(val)
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def _v(val: object) -> str:
    if val is None:
        return "0"
    return str(val)
